export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './customers.serviceInterface';
export * from './inventory.service';
import { InventoryService } from './inventory.service';
export * from './inventory.serviceInterface';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './menu.serviceInterface';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './orders.serviceInterface';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './payments.serviceInterface';
export * from './reports.service';
import { ReportsService } from './reports.service';
export * from './reports.serviceInterface';
export * from './reservations.service';
import { ReservationsService } from './reservations.service';
export * from './reservations.serviceInterface';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './reviews.serviceInterface';
export * from './staff.service';
import { StaffService } from './staff.service';
export * from './staff.serviceInterface';
export const APIS = [AuthService, CustomersService, InventoryService, MenuService, OrdersService, PaymentsService, ReportsService, ReservationsService, ReviewsService, StaffService];
