/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthResult } from '../model/models';
import { ChangePasswordCommand } from '../model/models';
import { ConfirmEmailChangeCommand } from '../model/models';
import { ConfirmEmailCommand } from '../model/models';
import { CurrentUserDto } from '../model/models';
import { ForgotPasswordCommand } from '../model/models';
import { LoginCommand } from '../model/models';
import { LogoutCommand } from '../model/models';
import { MessageResponseDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { RefreshTokenCommand } from '../model/models';
import { RegisterCommand } from '../model/models';
import { RegisterResponseDto } from '../model/models';
import { RequestEmailChangeCommand } from '../model/models';
import { ResendConfirmationCommand } from '../model/models';
import { ResetPasswordCommand } from '../model/models';
import { SetUserActiveStatusRequest } from '../model/models';
import { TokenValidationDto } from '../model/models';
import { ValidateTokenQuery } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/Auth/admin/users/{userId}/status
     * @param userId 
     * @param apiVersion 
     * @param setUserActiveStatusRequest 
     */
    apiAuthAdminUsersUserIdStatusPatch(userId: number, apiVersion?: string, setUserActiveStatusRequest?: SetUserActiveStatusRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/change-email-confirm
     * @param apiVersion 
     * @param confirmEmailChangeCommand 
     */
    apiAuthChangeEmailConfirmPost(apiVersion?: string, confirmEmailChangeCommand?: ConfirmEmailChangeCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/change-email-request
     * @param apiVersion 
     * @param requestEmailChangeCommand 
     */
    apiAuthChangeEmailRequestPost(apiVersion?: string, requestEmailChangeCommand?: RequestEmailChangeCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/change-password
     * @param apiVersion 
     * @param changePasswordCommand 
     */
    apiAuthChangePasswordPost(apiVersion?: string, changePasswordCommand?: ChangePasswordCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/confirm-email
     * @param apiVersion 
     * @param confirmEmailCommand 
     */
    apiAuthConfirmEmailPost(apiVersion?: string, confirmEmailCommand?: ConfirmEmailCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/delete-account
     * @param apiVersion 
     */
    apiAuthDeleteAccountPost(apiVersion?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/forgot-password
     * @param apiVersion 
     * @param forgotPasswordCommand 
     */
    apiAuthForgotPasswordPost(apiVersion?: string, forgotPasswordCommand?: ForgotPasswordCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/login
     * @param apiVersion 
     * @param loginCommand 
     */
    apiAuthLoginPost(apiVersion?: string, loginCommand?: LoginCommand, extraHttpRequestParams?: any): Observable<AuthResult>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/logout
     * @param apiVersion 
     * @param logoutCommand 
     */
    apiAuthLogoutPost(apiVersion?: string, logoutCommand?: LogoutCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/Auth/me
     * @param apiVersion 
     */
    apiAuthMeGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<CurrentUserDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/refresh
     * @param apiVersion 
     * @param refreshTokenCommand 
     */
    apiAuthRefreshPost(apiVersion?: string, refreshTokenCommand?: RefreshTokenCommand, extraHttpRequestParams?: any): Observable<AuthResult>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/register
     * @param apiVersion 
     * @param registerCommand 
     */
    apiAuthRegisterPost(apiVersion?: string, registerCommand?: RegisterCommand, extraHttpRequestParams?: any): Observable<RegisterResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/resend-confirmation
     * @param apiVersion 
     * @param resendConfirmationCommand 
     */
    apiAuthResendConfirmationPost(apiVersion?: string, resendConfirmationCommand?: ResendConfirmationCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/reset-password
     * @param apiVersion 
     * @param resetPasswordCommand 
     */
    apiAuthResetPasswordPost(apiVersion?: string, resetPasswordCommand?: ResetPasswordCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Auth/validate-token
     * @param apiVersion 
     * @param validateTokenQuery 
     */
    apiAuthValidateTokenPost(apiVersion?: string, validateTokenQuery?: ValidateTokenQuery, extraHttpRequestParams?: any): Observable<TokenValidationDto>;

}
