/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddAddressCommand } from '../model/models';
import { CreateCustomerProfileCommand } from '../model/models';
import { CustomerAddressDto } from '../model/models';
import { CustomerProfileDto } from '../model/models';
import { LoyaltyPointsDto } from '../model/models';
import { MessageResponseDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateAddressRequest } from '../model/models';
import { UpdateCustomerProfileCommand } from '../model/models';
import { UploadImageResponseDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CustomersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/Customers/addresses/{addressId}
     * @param addressId 
     * @param apiVersion 
     */
    apiCustomersAddressesAddressIdDelete(addressId: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/Customers/addresses/{addressId}
     * @param addressId 
     * @param apiVersion 
     * @param updateAddressRequest 
     */
    apiCustomersAddressesAddressIdPut(addressId: number, apiVersion?: string, updateAddressRequest?: UpdateAddressRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/Customers/addresses
     * @param apiVersion 
     */
    apiCustomersAddressesGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<CustomerAddressDto>>;

    /**
     * 
     * 
     * @endpoint post /api/Customers/addresses
     * @param apiVersion 
     * @param addAddressCommand 
     */
    apiCustomersAddressesPost(apiVersion?: string, addAddressCommand?: AddAddressCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/Customers/loyalty
     * @param apiVersion 
     */
    apiCustomersLoyaltyGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<LoyaltyPointsDto>;

    /**
     * 
     * 
     * @endpoint get /api/Customers/profile
     * @param apiVersion 
     */
    apiCustomersProfileGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<CustomerProfileDto>;

    /**
     * 
     * 
     * @endpoint post /api/Customers/profile/image
     * @param apiVersion 
     * @param file 
     */
    apiCustomersProfileImagePost(apiVersion?: string, file?: Blob, extraHttpRequestParams?: any): Observable<UploadImageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/Customers/profile
     * @param apiVersion 
     * @param createCustomerProfileCommand 
     */
    apiCustomersProfilePost(apiVersion?: string, createCustomerProfileCommand?: CreateCustomerProfileCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint put /api/Customers/profile
     * @param apiVersion 
     * @param updateCustomerProfileCommand 
     */
    apiCustomersProfilePut(apiVersion?: string, updateCustomerProfileCommand?: UpdateCustomerProfileCommand, extraHttpRequestParams?: any): Observable<{}>;

}
