/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdjustInventoryCommand } from '../model/models';
import { InventoryItemDto } from '../model/models';
import { InventoryTransactionDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { RestockItemCommand } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InventoryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/inventory/adjust
     * @param apiVersion 
     * @param adjustInventoryCommand 
     */
    apiInventoryAdjustPost(apiVersion?: string, adjustInventoryCommand?: AdjustInventoryCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/inventory/low-stock
     * @param apiVersion 
     */
    apiInventoryLowStockGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<InventoryItemDto>>;

    /**
     * 
     * 
     * @endpoint get /api/inventory/report
     * @param dateFrom 
     * @param dateTo 
     * @param apiVersion 
     */
    apiInventoryReportGet(dateFrom?: string, dateTo?: string, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<InventoryTransactionDto>>;

    /**
     * 
     * 
     * @endpoint post /api/inventory/restock
     * @param apiVersion 
     * @param restockItemCommand 
     */
    apiInventoryRestockPost(apiVersion?: string, restockItemCommand?: RestockItemCommand, extraHttpRequestParams?: any): Observable<{}>;

}
