/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddOptionCommand } from '../model/models';
import { CategoryDto } from '../model/models';
import { CreateCategoryCommand } from '../model/models';
import { CreateMenuItemCommand } from '../model/models';
import { CreateOptionGroupCommand } from '../model/models';
import { MenuItemDetailDto } from '../model/models';
import { MenuItemDto } from '../model/models';
import { MessageResponseDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateMenuItemRequest } from '../model/models';
import { UploadImageResponseDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MenuServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/menu/categories/{categoryId}/image
     * @param categoryId 
     * @param apiVersion 
     * @param file 
     */
    apiMenuCategoriesCategoryIdImagePost(categoryId: number, apiVersion?: string, file?: Blob, extraHttpRequestParams?: any): Observable<UploadImageResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/menu/categories
     * @param activeOnly 
     * @param apiVersion 
     */
    apiMenuCategoriesGet(activeOnly?: boolean, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<CategoryDto>>;

    /**
     * 
     * 
     * @endpoint post /api/menu/categories
     * @param apiVersion 
     * @param createCategoryCommand 
     */
    apiMenuCategoriesPost(apiVersion?: string, createCategoryCommand?: CreateCategoryCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint get /api/menu/featured
     * @param apiVersion 
     */
    apiMenuFeaturedGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<MenuItemDto>>;

    /**
     * 
     * 
     * @endpoint get /api/menu/items
     * @param categoryId 
     * @param availableOnly 
     * @param search 
     * @param apiVersion 
     */
    apiMenuItemsGet(categoryId?: number, availableOnly?: boolean, search?: string, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<MenuItemDto>>;

    /**
     * 
     * 
     * @endpoint delete /api/menu/items/{id}
     * @param id 
     * @param apiVersion 
     */
    apiMenuItemsIdDelete(id: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/menu/items/{id}
     * @param id 
     * @param apiVersion 
     */
    apiMenuItemsIdGet(id: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<MenuItemDetailDto>;

    /**
     * 
     * 
     * @endpoint put /api/menu/items/{id}
     * @param id 
     * @param apiVersion 
     * @param updateMenuItemRequest 
     */
    apiMenuItemsIdPut(id: number, apiVersion?: string, updateMenuItemRequest?: UpdateMenuItemRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/menu/items/{itemId}/image
     * @param itemId 
     * @param apiVersion 
     * @param file 
     */
    apiMenuItemsItemIdImagePost(itemId: number, apiVersion?: string, file?: Blob, extraHttpRequestParams?: any): Observable<UploadImageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/menu/items/{itemId}/option-groups
     * @param itemId 
     * @param apiVersion 
     * @param createOptionGroupCommand 
     */
    apiMenuItemsItemIdOptionGroupsPost(itemId: number, apiVersion?: string, createOptionGroupCommand?: CreateOptionGroupCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/menu/items
     * @param apiVersion 
     * @param createMenuItemCommand 
     */
    apiMenuItemsPost(apiVersion?: string, createMenuItemCommand?: CreateMenuItemCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/menu/option-groups/{groupId}/options
     * @param groupId 
     * @param apiVersion 
     * @param addOptionCommand 
     */
    apiMenuOptionGroupsGroupIdOptionsPost(groupId: number, apiVersion?: string, addOptionCommand?: AddOptionCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

}
