/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddOrderNoteRequest } from '../model/models';
import { AssignDriverRequest } from '../model/models';
import { CancelOrderRequest } from '../model/models';
import { CreateOrderCommand } from '../model/models';
import { OrderDetailDto } from '../model/models';
import { OrderDto } from '../model/models';
import { OrderSummaryDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { UpdateOrderStatusRequest } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OrdersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/orders/active
     * @param apiVersion 
     */
    apiOrdersActiveGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<OrderSummaryDto>>;

    /**
     * 
     * 
     * @endpoint get /api/orders/history
     * @param dateFrom 
     * @param dateTo 
     * @param apiVersion 
     */
    apiOrdersHistoryGet(dateFrom?: string, dateTo?: string, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<OrderSummaryDto>>;

    /**
     * 
     * 
     * @endpoint post /api/orders/{id}/assign-driver
     * @param id 
     * @param apiVersion 
     * @param assignDriverRequest 
     */
    apiOrdersIdAssignDriverPost(id: number, apiVersion?: string, assignDriverRequest?: AssignDriverRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/orders/{id}/cancel
     * @param id 
     * @param apiVersion 
     * @param cancelOrderRequest 
     */
    apiOrdersIdCancelPost(id: number, apiVersion?: string, cancelOrderRequest?: CancelOrderRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/orders/{id}
     * @param id 
     * @param apiVersion 
     */
    apiOrdersIdGet(id: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<OrderDetailDto>;

    /**
     * 
     * 
     * @endpoint post /api/orders/{id}/notes
     * @param id 
     * @param apiVersion 
     * @param addOrderNoteRequest 
     */
    apiOrdersIdNotesPost(id: number, apiVersion?: string, addOrderNoteRequest?: AddOrderNoteRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/orders/{id}/status
     * @param id 
     * @param apiVersion 
     * @param updateOrderStatusRequest 
     */
    apiOrdersIdStatusPut(id: number, apiVersion?: string, updateOrderStatusRequest?: UpdateOrderStatusRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/orders/my
     * @param apiVersion 
     */
    apiOrdersMyGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<OrderSummaryDto>>;

    /**
     * 
     * 
     * @endpoint post /api/orders
     * @param apiVersion 
     * @param createOrderCommand 
     */
    apiOrdersPost(apiVersion?: string, createOrderCommand?: CreateOrderCommand, extraHttpRequestParams?: any): Observable<OrderDto>;

}
