/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaymentDto } from '../model/models';
import { PaymentResponseDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ProcessPaymentCommand } from '../model/models';
import { RefundPaymentCommand } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PaymentsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/payments/history
     * @param orderId 
     * @param apiVersion 
     */
    apiPaymentsHistoryGet(orderId?: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<PaymentDto>>;

    /**
     * 
     * 
     * @endpoint post /api/payments/process
     * @param apiVersion 
     * @param processPaymentCommand 
     */
    apiPaymentsProcessPost(apiVersion?: string, processPaymentCommand?: ProcessPaymentCommand, extraHttpRequestParams?: any): Observable<PaymentResponseDto>;

    /**
     * 
     * 
     * @endpoint post /api/payments/refund
     * @param apiVersion 
     * @param refundPaymentCommand 
     */
    apiPaymentsRefundPost(apiVersion?: string, refundPaymentCommand?: RefundPaymentCommand, extraHttpRequestParams?: any): Observable<{}>;

}
