/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AnalyticsDto } from '../model/models';
import { PopularItemDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { SalesReportDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReportsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/reports/customer-analytics
     * @param apiVersion 
     */
    apiReportsCustomerAnalyticsGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<AnalyticsDto>;

    /**
     * 
     * 
     * @endpoint get /api/reports/popular-items
     * @param dateFrom 
     * @param dateTo 
     * @param limit 
     * @param apiVersion 
     */
    apiReportsPopularItemsGet(dateFrom?: string, dateTo?: string, limit?: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<PopularItemDto>>;

    /**
     * 
     * 
     * @endpoint get /api/reports/sales
     * @param dateFrom 
     * @param dateTo 
     * @param apiVersion 
     */
    apiReportsSalesGet(dateFrom?: string, dateTo?: string, apiVersion?: string, extraHttpRequestParams?: any): Observable<SalesReportDto>;

}
