/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CancelReservationCommand } from '../model/models';
import { ConfirmReservationCommand } from '../model/models';
import { CreateReservationCommand } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ReservationDto } from '../model/models';
import { TableAvailabilityDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReservationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/reservations/available-tables
     * @param reservationDate 
     * @param reservationTime 
     * @param partySize 
     * @param apiVersion 
     */
    apiReservationsAvailableTablesGet(reservationDate?: string, reservationTime?: string, partySize?: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<TableAvailabilityDto>>;

    /**
     * 
     * 
     * @endpoint post /api/reservations/{id}/cancel
     * @param id 
     * @param apiVersion 
     * @param cancelReservationCommand 
     */
    apiReservationsIdCancelPost(id: number, apiVersion?: string, cancelReservationCommand?: CancelReservationCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/reservations/{id}/confirm
     * @param id 
     * @param apiVersion 
     * @param confirmReservationCommand 
     */
    apiReservationsIdConfirmPost(id: number, apiVersion?: string, confirmReservationCommand?: ConfirmReservationCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/reservations/my
     * @param apiVersion 
     */
    apiReservationsMyGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<ReservationDto>>;

    /**
     * 
     * 
     * @endpoint post /api/reservations
     * @param apiVersion 
     * @param createReservationCommand 
     */
    apiReservationsPost(apiVersion?: string, createReservationCommand?: CreateReservationCommand, extraHttpRequestParams?: any): Observable<ReservationDto>;

    /**
     * 
     * 
     * @endpoint get /api/reservations/today
     * @param apiVersion 
     */
    apiReservationsTodayGet(apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<ReservationDto>>;

}
