/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateReviewCommand } from '../model/models';
import { MessageResponseDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { RespondToReviewCommand } from '../model/models';
import { ReviewDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReviewsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/reviews/{id}/respond
     * @param id 
     * @param apiVersion 
     * @param respondToReviewCommand 
     */
    apiReviewsIdRespondPost(id: number, apiVersion?: string, respondToReviewCommand?: RespondToReviewCommand, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/reviews/menu-items/{menuItemId}
     * @param menuItemId 
     * @param apiVersion 
     */
    apiReviewsMenuItemsMenuItemIdGet(menuItemId: number, apiVersion?: string, extraHttpRequestParams?: any): Observable<Array<ReviewDto>>;

    /**
     * 
     * 
     * @endpoint post /api/reviews
     * @param apiVersion 
     * @param createReviewCommand 
     */
    apiReviewsPost(apiVersion?: string, createReviewCommand?: CreateReviewCommand, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

}
