/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateStaffProfileRequest } from '../model/models';
import { MessageResponseDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StaffServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/staff
     * @param apiVersion 
     * @param createStaffProfileRequest 
     */
    apiStaffPost(apiVersion?: string, createStaffProfileRequest?: CreateStaffProfileRequest, extraHttpRequestParams?: any): Observable<MessageResponseDto>;

}
