/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddOptionCommand { 
    optionGroupId?: number;
    name?: string | null;
    priceAdjustment?: number;
    caloriesAdjustment?: number;
    isAvailable?: boolean;
    isDefault?: boolean;
    displayOrder?: number;
}

