/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderNoteType } from './orderNoteType';


export interface AddOrderNoteRequest { 
    noteType?: OrderNoteType;
    note?: string | null;
}
export namespace AddOrderNoteRequest {
}


