/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResult { 
    userId?: number;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    accessToken?: string | null;
    refreshToken?: string | null;
    expiresAt?: string;
    roles?: Array<string> | null;
}

