/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateMenuItemCommand { 
    categoryId?: number;
    name?: string | null;
    description?: string | null;
    price?: number;
    imageUrl?: string | null;
    thumbnailUrl?: string | null;
    isAvailable?: boolean;
    isFeatured?: boolean;
    preparationTimeMinutes?: number;
    calories?: number | null;
    spiceLevel?: number;
    isVegetarian?: boolean;
    isVegan?: boolean;
    isGlutenFree?: boolean;
    isDairyFree?: boolean;
    isNutFree?: boolean;
    allergenInfo?: string | null;
    maxQuantityPerOrder?: number;
}

