/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderType } from './orderType';
import { CreateOrderItemDto } from './createOrderItemDto';


export interface CreateOrderDto { 
    orderType?: OrderType;
    deliveryAddressId?: number | null;
    customerNotes?: string | null;
    kitchenNotes?: string | null;
    deliveryNotes?: string | null;
    tipAmount?: number | null;
    items?: Array<CreateOrderItemDto> | null;
}
export namespace CreateOrderDto {
}


