/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateReviewCommand { 
    orderId?: number;
    rating?: number;
    foodRating?: number | null;
    serviceRating?: number | null;
    deliveryRating?: number | null;
    reviewText?: string | null;
}

