/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateStaffProfileRequest { 
    userId?: number;
    phone?: string | null;
    profileImageUrl?: string | null;
}

