/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateReservationDto { 
    tableId?: number;
    reservationDate?: string;
    reservationTime?: string;
    partySize?: number;
    specialRequests?: string | null;
    customerNotes?: string | null;
}

