/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CurrentUserDto { 
    isAuthenticated?: boolean;
    userId?: number | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    emailConfirmed?: boolean;
    roles?: Array<string> | null;
}

