/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerProfileDto { 
    email?: string | null;
    phone?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string | null;
    profileImageUrl?: string | null;
    isVerified?: boolean;
    loyaltyPoints?: number;
    totalOrders?: number;
    totalSpent?: number;
    averageRating?: number | null;
    createdAt?: string;
}

