/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InventoryItemDto { 
    id?: number;
    name?: string | null;
    sku?: string | null;
    unitOfMeasure?: string | null;
    currentQuantity?: number;
    minimumQuantity?: number;
    unitCost?: number;
    isLowStock?: boolean;
}

