/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryTransactionType } from './inventoryTransactionType';


export interface InventoryTransactionDto { 
    id?: number;
    inventoryItemId?: number;
    transactionType?: InventoryTransactionType;
    quantityChange?: number;
    quantityAfter?: number;
    createdAt?: string;
    notes?: string | null;
}
export namespace InventoryTransactionDto {
}


