/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const InventoryTransactionType = {
    Restock: 'restock',
    Usage: 'usage',
    Waste: 'waste',
    Adjustment: 'adjustment',
    Return: 'return'
} as const;
export type InventoryTransactionType = typeof InventoryTransactionType[keyof typeof InventoryTransactionType];

