/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OptionSelectionType = {
    Single: 'single',
    Multiple: 'multiple'
} as const;
export type OptionSelectionType = typeof OptionSelectionType[keyof typeof OptionSelectionType];

