/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OptionSelectionType } from './optionSelectionType';
import { OptionDto } from './optionDto';


export interface OptionGroupDto { 
    id?: number;
    name?: string | null;
    description?: string | null;
    isRequired?: boolean;
    selectionType?: OptionSelectionType;
    minSelections?: number;
    maxSelections?: number;
    displayOrder?: number;
    options?: Array<OptionDto> | null;
}
export namespace OptionGroupDto {
}


