/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderNoteType = {
    Customer: 'customer',
    Kitchen: 'kitchen',
    Delivery: 'delivery'
} as const;
export type OrderNoteType = typeof OrderNoteType[keyof typeof OrderNoteType];

