/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const OrderStatus = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Preparing: 'preparing',
    Ready: 'ready',
    OutForDelivery: 'outForDelivery',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;
export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];

