/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';


export interface OrderSummaryDto { 
    id?: number;
    orderNumber?: string | null;
    orderStatus?: OrderStatus;
    totalAmount?: number;
    createdAt?: string;
}
export namespace OrderSummaryDto {
}


