/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';
import { OrderType } from './orderType';
import { OrderItemDto } from './orderItemDto';


export interface OrderDetailDto { 
    id?: number;
    orderNumber?: string | null;
    orderStatus?: OrderStatus;
    orderType?: OrderType;
    subtotal?: number;
    taxRate?: number;
    taxAmount?: number;
    deliveryFee?: number;
    discountAmount?: number;
    tipAmount?: number;
    totalAmount?: number;
    customerNotes?: string | null;
    kitchenNotes?: string | null;
    deliveryNotes?: string | null;
    createdAt?: string;
    updatedAt?: string;
    items?: Array<OrderItemDto> | null;
}
export namespace OrderDetailDto {
}


