/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemOptionDto } from './orderItemOptionDto';


export interface OrderItemDto { 
    itemId?: number;
    name?: string | null;
    quantity?: number;
    unitPrice?: number;
    subtotal?: number;
    itemNotes?: string | null;
    options?: Array<OrderItemOptionDto> | null;
}

