/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderItemOptionDto { 
    optionId?: number;
    optionGroupName?: string | null;
    optionName?: string | null;
    priceAdjustment?: number;
}

