/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';
import { OrderType } from './orderType';


export interface OrderDto { 
    id?: number;
    orderNumber?: string | null;
    orderStatus?: OrderStatus;
    orderType?: OrderType;
    totalAmount?: number;
    createdAt?: string;
}
export namespace OrderDto {
}


