/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PaymentStatus = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Refunded: 'refunded',
    PartiallyRefunded: 'partiallyRefunded'
} as const;
export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];

