/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethod } from './paymentMethod';
import { PaymentStatus } from './paymentStatus';


export interface PaymentDto { 
    id?: number;
    orderId?: number;
    paymentMethod?: PaymentMethod;
    amount?: number;
    paymentStatus?: PaymentStatus;
    paymentDate?: string;
}
export namespace PaymentDto {
}


