/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentStatus } from './paymentStatus';


export interface PaymentResponseDto { 
    paymentId?: number;
    orderId?: number;
    status?: PaymentStatus;
    amount?: number;
}
export namespace PaymentResponseDto {
}


