/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethod } from './paymentMethod';


export interface ProcessPaymentCommand { 
    orderId?: number;
    paymentMethod?: PaymentMethod;
    amount?: number;
}
export namespace ProcessPaymentCommand {
}


