/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationStatus } from './reservationStatus';


export interface ReservationDto { 
    id?: number;
    reservationDate?: string;
    reservationTime?: string;
    partySize?: number;
    status?: ReservationStatus;
    confirmationCode?: string | null;
}
export namespace ReservationDto {
}


