/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ReservationStatus = {
    Pending: 'pending',
    Confirmed: 'confirmed',
    Seated: 'seated',
    Completed: 'completed',
    Cancelled: 'cancelled',
    NoShow: 'noShow'
} as const;
export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];

