/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestockItemCommand { 
    inventoryItemId?: number;
    quantityAdded?: number;
    unitCost?: number | null;
    notes?: string | null;
}

