/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalesReportDto { 
    dateFrom?: string | null;
    dateTo?: string | null;
    totalSales?: number;
    totalOrders?: number;
    averageOrderValue?: number;
}

