/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateMenuItemRequest { 
    categoryId?: number | null;
    name?: string | null;
    description?: string | null;
    price?: number | null;
    imageUrl?: string | null;
    thumbnailUrl?: string | null;
    isAvailable?: boolean | null;
    isFeatured?: boolean | null;
    preparationTimeMinutes?: number | null;
    calories?: number | null;
    spiceLevel?: number | null;
    isVegetarian?: boolean | null;
    isVegan?: boolean | null;
    isGlutenFree?: boolean | null;
    isDairyFree?: boolean | null;
    isNutFree?: boolean | null;
    allergenInfo?: string | null;
    maxQuantityPerOrder?: number | null;
}

