/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';


export interface UpdateOrderStatusRequest { 
    status?: OrderStatus;
    notes?: string | null;
}
export namespace UpdateOrderStatusRequest {
}


