/**
 * Restaurant API v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const UserRole = {
    Customer: 'customer',
    Staff: 'staff',
    Chef: 'chef',
    Manager: 'manager',
    Admin: 'admin',
    Delivery: 'delivery'
} as const;
export type UserRole = typeof UserRole[keyof typeof UserRole];

